on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          git config user.name ${{ secrets.NAME }}
          git config user.email ${{ secrets.EMAIL }}
          yarn
          yarn build
          git add -f dist
          git commit -m "build" && git push
          echo "success"
